spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/ChatDataBase

  flyway:
    default-schema: test_schema
    baseline-on-migrate: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: test_schema
        format_sql: true

server:
  port: 9000
