spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/ChatDataBase

  flyway:
    default-schema: test_schema
    baseline-on-migrate: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: test_schema
        format_sql: true

server:
  port: 9000
  error:
    include-message: always

logging:
  file:
    name: log/mylog.log
  level:
    root: info
  pattern:
    dateformat: dd-MM-yyyy HH:mm:ss
    file: "%d{dd-MM-yyyy HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"

jwt:
  secret: "k1skSKKks_)0992kdsfl#@kdgjl!kdjg{kjdj,zjjjgfdjgj32JKHKJHjKksjkdhgkjhdksjKK333"