create table if not exists users
(
    id   bigint generated by default as identity primary key,
    user_name varchar unique not null,
    created_at timestamp not null
);

/*
create table if not exists chat
(
    id   bigint generated by default as identity primary key,
    name_chat varchar unique not null
);

create table if not exists message
(
    id bigint generated by default as identity primary key,
    chat_id   bigint not null references chat (id),
    user_id   bigint not null references users (id),
    text_message varchar(100) not null
);*/
