create table if not exists chats
(
    id   bigint generated by default as identity primary key,
    name_chat varchar unique not null,
    created_at timestamp not null
);

create table if not exists chats_users
(
     id bigint generated by default as identity primary key,
     chat_id bigint not null references chats(id),
     user_id bigint not null references users(id)
);
