create table if not exists messages
(
    id bigint generated by default as identity primary key,
    chat_id bigint not null references chats(id),
    user_id bigint not null references users(id),
    text_message varchar not null,
    created_at timestamp not null
);
